global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'warehouse-service'
    static_configs:
      - targets: ['warehouse-service:8084']
    metrics_path: '/metrics' 