global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:50051']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:50052']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:50053']

  - job_name: 'warehouse-service'
    static_configs:
      - targets: ['warehouse-service:50054'] 